
import { StyleSheet} from 'react-native';

const theme = StyleSheet.create({
    main_screen: {
        width:'100%',
        height:'100%',
    },
    heading_font:{
        fontFamily:"Barlow_Bold"
    },
    text_font:{
        fontFamily:"Barlow_Regular"
    },
    /// Font Sizing
    f_10: { fontSize: 10},
    f_12: { fontSize: 12},
    f_14: { fontSize: 14},
    f_16: { fontSize: 16},
    f_18: { fontSize: 18},
    f_20: { fontSize: 20},
    f_22: { fontSize: 22},
    f_24: { fontSize: 24},
    f_28: { fontSize: 28},
    f_30: { fontSize: 30},
    f_32: { fontSize: 32},
    f_34: { fontSize: 34},
    f_36: { fontSize: 36},
    f_w_bold: { fontWeight: "bold"},

    ///Text Colors
    orange: { color: '#E66A71' },
    purple: { color: '#CB587F' },
    gray: { color: '#707070' },
    green: { color: '#126D5D' },
    white: { color: 'white' },
    black: { color: '#000000' },
    theme_heading_color: { color:'#000000',fontWeight:'900'},

    /// Background Colors
    bg_green: { backgroundColor:'#449284'},
    bg_purple: { backgroundColor:'#CB587F'},
    bg_orange: { backgroundColor:'#F58220'},
    bg_gray: { backgroundColor:'#707070'},
    bg_light_gray: { backgroundColor:'#F8F8F8'},
    bg_pink: { backgroundColor:'#cb587f'},
    bg_danger: { backgroundColor:'#e81616'},
    bg_white: { backgroundColor:'white'},
    /// Border Colors
    border_green: { borderColor: '#449284' },
    border_orange: { borderColor: '#F58220' },
    border_gray: { borderColor: '#E9E8E8' },
    border_light_gray: { borderColor: '#F8F8F8' },


    /// Borders
    border: { borderWidth:1 },


    /// Flex
    row: { flexDirection: 'row'},

    // justify content
    jc_center: { justifyContent: 'center'},
    jc_flex_end: { justifyContent: 'flex-end'},
    jc_flex_start: { justifyContent: 'flex-start'},
    jc_flex_around: { justifyContent: 'space-around'},
    jc_space_between: { justifyContent: 'space-between' },
    jc_space_evenly: { justifyContent: 'space-evenly' },

    // Width
    w_10: { width: '10%'},
    w_15: { width: '15%'},
    w_20: { width: '20%'},
    w_25: { width: '25%'},
    w_30: { width: '30%'},
    w_35: { width: '35%'},
    w_40: { width: '40%'},
    w_45: { width: '45%'},
    w_50: { width: '50%'},
    w_55: { width: '55%'},
    w_60: { width: '60%'},
    w_65: { width: '65%'},
    w_70: { width: '70%'},
    w_75: { width: '75%'},
    w_80: { width: '80%'},
    w_85: { width: '85%'},
    w_90: { width: '90%'},
    w_95: { width: '95%'},
    w_100: { width: '100%'},

    wp_10: { width: 10 },
    wp_20: { width: 20 },
    wp_30: { width: 30 },
    wp_40: { width: 40 },
    wp_50: { width: 50 },
    wp_60: { width: 60 },
    wp_70: { width: 70 },
    wp_80: { width: 80 },
    wp_90: { width: 90 },
    wp_100: {width: 100 },
    // Height
    h_10: { height: '10%' },
    h_20: { height: '20%' },
    h_30: { height: '30%' },
    h_40: { height: '40%' },
    h_50: { height: '50%' },
    h_60: { height: '60%' },
    h_70: { height: '70%' },
    h_80: { height: '80%' },
    h_90: { height: '90%' },
    h_100: { height: '100%' },

    hp_10: { height: 10 },
    hp_20: { height: 20 },
    hp_30: { height: 30 },
    hp_40: { height: 40 },
    hp_50: { height: 50 },
    hp_60: { height: 60 },
    hp_70: { height: 70 },
    hp_80: { height: 80 },
    hp_90: { height: 90 },
    hp_100: { height: 100 },

    /// Align Item
    align_center :{alignItems: 'center'},
    align_baseline :{alignItems: 'baseline'},
    align_flex_end :{alignItems: 'flex-end'},
    align_flex_start :{alignItems: 'flex-start'},
    align_stretch :{alignItems: 'stretch'},

    // Padding
    p_0: { padding: 0},
    p_5: { padding: 5},
    p_10: { padding: 10},
    p_15: { padding: 15},
    p_20: { padding: 20},
    p_25: { padding: 25},
    p_30: { padding: 30},
    p_35: { padding: 35},
    p_40: { padding: 40},
    // Padding Vertical
    py_0: { paddingVertical: 0 },
    py_10: { paddingVertical: 10 },
    py_15: { paddingVertical: 15 },
    py_20: { paddingVertical: 20 },
    py_25: { paddingVertical: 25 },
    py_30: { paddingVertical: 30 },
    py_35: { paddingVertical: 35 },
    py_40: { paddingVertical: 40 },
    // Padding Horizontal
    px_0: { paddingHorizontal: 0 },
    px_5: { paddingHorizontal: 5 },
    px_10: { paddingHorizontal: 10 },
    px_15: { paddingHorizontal: 15 },
    px_20: { paddingHorizontal: 20 },
    px_25: { paddingHorizontal: 25 },
    px_30: { paddingHorizontal: 30 },
    px_35: { paddingHorizontal: 35 },
    px_40: { paddingHorizontal: 40 },
    // Padding Left
    pl_0: { paddingLeft: 0 },
    pl_5: { paddingLeft: 5 },
    pl_10: { paddingLeft: 10 },
    pl_15: { paddingLeft: 15 },
    pl_20: { paddingLeft: 20 },
    pl_25: { paddingLeft: 25 },
    pl_30: { paddingLeft: 30 },
    pl_35: { paddingLeft: 35 },
    pl_40: { paddingLeft: 40 },
    // Padding Right
    pr_0: { paddingRight: 0 },
    pr_5: { paddingRight: 5 },
    pr_10: { paddingRight: 10 },
    pr_15: { paddingRight: 15 },
    pr_20: { paddingRight: 20 },
    pr_25: { paddingRight: 25 },
    pr_30: { paddingRight: 30 },
    pr_35: { paddingRight: 35 },
    pr_40: { paddingRight: 40 },
    // Padding Top
    pt_0: { paddingTop: 0 },
    pt_5: { paddingTop: 5 },
    pt_10: { paddingTop: 10 },
    pt_15: { paddingTop: 15 },
    pt_20: { paddingTop: 20 },
    pt_25: { paddingTop: 25 },
    pt_30: { paddingTop: 30 },
    pt_35: { paddingTop: 35 },
    pt_40: { paddingTop: 40 },
    // Padding Bottom
    pb_0: { paddingBottom: 0 },
    pb_5: { paddingBottom: 5 },
    pb_10: { paddingBottom: 10 },
    pb_15: { paddingBottom: 15 },
    pb_20: { paddingBottom: 20 },
    pb_25: { paddingBottom: 25 },
    pb_30: { paddingBottom: 30 },
    pb_35: { paddingBottom: 35 },
    pb_40: { paddingBottom: 40 },

    // Margins
    m_0: { margin: 0 },
    m_5: { margin: 5 },
    m_10: { margin: 10 },
    m_15: { margin: 15 },
    m_20: { margin: 20 },
    m_25: { margin: 25 },
    m_30: { margin: 30 },
    m_35: { margin: 35 },
    m_40: { margin: 40 },
    // Margin Vertical
    my_0: { marginVertical: 0 },
    my_5: { marginVertical: 5 },
    my_10: { marginVertical: 10 },
    my_15: { marginVertical: 15 },
    my_20: { marginVertical: 20 },
    my_25: { marginVertical: 25 },
    my_30: { marginVertical: 30 },
    my_35: { marginVertical: 35 },
    my_40: { marginVertical: 40 },
    // Margin Horizontal
    mx_0: { marginHorizontal: 0 },
    mx_5: { marginHorizontal: 5 },
    mx_10: { marginHorizontal: 10 },
    mx_15: { marginHorizontal: 15 },
    mx_20: { marginHorizontal: 20 },
    mx_25: { marginHorizontal: 25 },
    mx_30: { marginHorizontal: 30 },
    mx_35: { marginHorizontal: 35 },
    mx_40: { marginHorizontal: 40 },
    // Margin Left
    ml_0: { marginLeft: 0 },
    ml_5: { marginLeft: 5 },
    ml_10: { marginLeft: 10 },
    ml_15: { marginLeft: 15 },
    ml_20: { marginLeft: 20 },
    ml_25: { marginLeft: 25 },
    ml_30: { marginLeft: 30 },
    ml_35: { marginLeft: 35 },
    ml_40: { marginLeft: 40 },
    // Margin Right
    mr_0: { marginRight: 0 },
    mr_5: { marginRight: 5 },
    mr_10: { marginRight: 10 },
    mr_15: { marginRight: 15 },
    mr_20: { marginRight: 20 },
    mr_25: { marginRight: 25 },
    mr_30: { marginRight: 30 },
    mr_35: { marginRight: 35 },
    mr_40: { marginRight: 40 },
    // Margin Top
    mt_0: { marginTop: 0 },
    mt_5: { marginTop: 5 },
    mt_10: { marginTop: 10 },
    mt_15: { marginTop: 15 },
    mt_20: { marginTop: 20 },
    mt_25: { marginTop: 25 },
    mt_30: { marginTop: 30 },
    mt_35: { marginTop: 35 },
    mt_40: { marginTop: 40 },
    // Margin Bottom
    mb_0: { marginBottom: 0 },
    mb_5: { marginBottom: 5 },
    mb_10: { marginBottom: 10 },
    mb_15: { marginBottom: 15 },
    mb_20: { marginBottom: 20 },
    mb_25: { marginBottom: 25 },
    mb_30: { marginBottom: 30 },
    mb_35: { marginBottom: 35 },
    mb_40: { marginBottom: 40 },
    /// absolute
    absolute:{ position: 'absolute'},
    /// Border Radius
    br_0:{borderRadius: 0},
    br_5:{borderRadius: 5},
    br_10:{borderRadius: 10},
    br_15:{borderRadius: 15},
    br_20:{borderRadius: 20},
    br_25:{borderRadius: 25},
    br_30:{borderRadius: 30},
    br_35:{borderRadius: 35},
    br_40:{borderRadius: 40},
    br_45:{borderRadius: 45},
    br_50:{borderRadius: 50},

    /// Border Bottom Start Radius
    brbs_5: { borderBottomStartRadius: 5 },
    brbs_10: { borderBottomEndRadius: 10 },
    brbs_15: { borderBottomEndRadius: 15 },
    brbs_20: { borderBottomEndRadius: 20 },
    brbs_25: { borderBottomEndRadius: 25 },
    brbs_30: { borderBottomEndRadius: 30 },
    brbs_35: { borderBottomEndRadius: 35 },
    brbs_40: { borderBottomEndRadius: 40 },
    brbs_45: { borderBottomEndRadius: 45 },
    brbs_50: { borderBottomEndRadius: 50 },
    /// Border Bottom End Radius
    brbe_5: { borderBottomEndRadius: 5 },
    brbe_10: { borderBottomEndRadius: 10 },
    brbe_15: { borderBottomEndRadius: 15 },
    brbe_20: { borderBottomEndRadius: 20 },
    brbe_25: { borderBottomEndRadius: 25 },
    brbe_30: { borderBottomEndRadius: 30 },
    brbe_35: { borderBottomEndRadius: 35 },
    brbe_40: { borderBottomEndRadius: 40 },
    brbe_45: { borderBottomEndRadius: 45 },
    brbe_50: { borderBottomEndRadius: 50 },

    /// Border Bottom Start Radius
    brbs_5: { borderBottomStartRadius: 5 },
    brbs_10: { borderBottomEndRadius: 10 },
    brbs_15: { borderBottomEndRadius: 15 },
    brbs_20: { borderBottomEndRadius: 20 },
    brbs_25: { borderBottomEndRadius: 25 },
    brbs_30: { borderBottomEndRadius: 30 },
    brbs_35: { borderBottomEndRadius: 35 },
    brbs_40: { borderBottomEndRadius: 40 },
    brbs_45: { borderBottomEndRadius: 45 },
    brbs_50: { borderBottomEndRadius: 50 },
    /// Border Bottom End Radius
    brbe_5: { borderBottomEndRadius: 5 },
    brbe_10: { borderBottomEndRadius: 10 },
    brbe_15: { borderBottomEndRadius: 15 },
    brbe_20: { borderBottomEndRadius: 20 },
    brbe_25: { borderBottomEndRadius: 25 },
    brbe_30: { borderBottomEndRadius: 30 },
    brbe_35: { borderBottomEndRadius: 35 },
    brbe_40: { borderBottomEndRadius: 40 },
    brbe_45: { borderBottomEndRadius: 45 },
    brbe_50: { borderBottomEndRadius: 50 },

    /// Text Align
    text_center: { textAlign: 'center' },
    text_justify: { textAlign: 'justify' },
    text_right: { textAlign: 'right' },
    text_left: { textAlign: 'left' },
    /// Text Align Vertical
    text_v_center: { textAlignVertical: 'center' },
    text_v_bottom: { textAlignVertical: 'bottom' },
    text_v_top: { textAlignVertical: 'top' },

});

export default theme;